### ISSUE TITLE
configList.json的问题

### ISSUE THREAD

**Issue by RealMoMo** [tuya/tuya-ui-bizbundle-android-config-values#5]
configList.json 不是全功能的设备详情的配置文件，少了共享设备、群组等等功能。
希望提供一份全配置的设备详情文件

**Comment by lixuecheng** [comment]
> configList.json 不是全功能的设备详情的配置文件，少了共享设备、群组等等功能。
> 希望提供一份全配置的设备详情文件

暂不支持共享设备、群组这些功能
